name: Build and publish Docker images

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - Dockerfile
    workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: frxyt/ark:latest